import { useEffect, useMemo, useState } from 'react'
import { api } from './api/client'
import './App.css'

const money = (value) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value || 0)
const dateTime = (value) => value ? new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'
const date = (value) => value ? new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(new Date(`${value}T00:00:00`)) : '—'

function Status({ value }) {
  const label = value === 'ESCALATED' ? 'Review required' : value?.charAt(0) + value?.slice(1).toLowerCase()
  return <span className={`status status--${value?.toLowerCase()}`}><span aria-hidden="true" />{label}</span>
}
function Notice({ children }) { return <div className="notice" role="alert">{children}</div> }

function CustomerFlow() {
  const [customers, setCustomers] = useState([]), [customerId, setCustomerId] = useState(''), [orders, setOrders] = useState([]), [orderId, setOrderId] = useState('')
  const [reason, setReason] = useState(''), [amount, setAmount] = useState(''), [loading, setLoading] = useState(true), [submitting, setSubmitting] = useState(false), [error, setError] = useState(''), [result, setResult] = useState(null)
  useEffect(() => { api.customers().then(setCustomers).catch(() => setError('We could not load customer accounts. Please refresh and try again.')).finally(() => setLoading(false)) }, [])
  async function chooseCustomer(id) { setCustomerId(id); setOrders([]); setOrderId(''); setAmount(''); setError(''); if (!id) return
    try { setOrders(await api.orders(id)) } catch (err) { setError(err.message) } }
  const selectedOrder = useMemo(() => orders.find((order) => String(order.id) === orderId), [orders, orderId])
  async function submit(event) { event.preventDefault(); setError(''); setResult(null); const requestedAmount = Number(amount)
    if (!customerId || !orderId || !reason.trim() || !amount) return setError('Select an account and order, then add a reason and requested amount.')
    if (!Number.isFinite(requestedAmount) || requestedAmount <= 0) return setError('Enter an amount greater than zero.')
    if (selectedOrder && requestedAmount > selectedOrder.amount) return setError('The requested amount cannot exceed the order amount.')
    setSubmitting(true); try { setResult(await api.createRefund({ customerId: Number(customerId), orderId: Number(orderId), reason: reason.trim(), requestedAmount })) } catch (err) { setError(err.message) } finally { setSubmitting(false) } }
  if (result) return <Result result={result} onStartOver={() => { setResult(null); setReason(''); setAmount(''); setOrderId('') }} />
  return <section className="request-shell"><div className="section-heading"><div><p className="eyebrow">Customer request</p><h1>Request a refund</h1><p>Tell us about the order and the amount you’re requesting. We’ll confirm the next step after review.</p></div><span className="step">Step 1 of 1</span></div>{error && <Notice>{error}</Notice>}
    <form onSubmit={submit} className="request-form"><label>Customer account<select value={customerId} onChange={(e) => chooseCustomer(e.target.value)} disabled={loading}><option value="">{loading ? 'Loading accounts…' : 'Select customer'}</option>{customers.map((c) => <option key={c.id} value={c.id}>{c.name} · {c.email}</option>)}</select></label><label>Order<select value={orderId} onChange={(e) => { setOrderId(e.target.value); const order = orders.find((item) => String(item.id) === e.target.value); if (order) setAmount(order.amount) }} disabled={!customerId || !orders.length}><option value="">{customerId && !orders.length ? 'Loading orders…' : 'Select order'}</option>{orders.map((o) => <option key={o.id} value={o.id}>{o.order_number} · {o.product_name} · {money(o.amount)}</option>)}</select></label>
      {selectedOrder && <div className="order-summary"><span>Order details</span><strong>{selectedOrder.product_name}</strong><small>{selectedOrder.order_number} · Placed {date(selectedOrder.order_date)} · Order total {money(selectedOrder.amount)}</small></div>}<div className="form-grid"><label>Requested amount<div className="input-prefix"><span>$</span><input type="number" min="0.01" max={selectedOrder?.amount} step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="0.00" /></div></label><label>Reason<textarea value={reason} onChange={(e) => setReason(e.target.value)} maxLength="1000" placeholder="Briefly describe what happened and how we can help." /></label></div><div className="form-footer"><p>We’ll use your request details to assess the applicable refund policy.</p><button className="button button--primary" disabled={submitting}>{submitting ? 'Submitting request…' : 'Submit refund request'}</button></div></form></section>
}
function Result({ result, onStartOver }) { const text = result.decision === 'APPROVED' ? 'Your refund request is approved.' : result.decision === 'DENIED' ? 'Your request could not be approved.' : 'Your request needs a quick human review.'
  return <section className="result"><div className="result-mark">{result.decision === 'APPROVED' ? '✓' : '!'}</div><Status value={result.decision} /><h1>{text}</h1><p className="result-lede">{result.ai.customerResponse}</p><div className="result-grid"><article><span>Requested amount</span><strong>{money(result.requestedAmount)}</strong></article><article><span>Order</span><strong>{result.order.order_number}</strong><small>{result.order.product_name}</small></article><article><span>Next steps</span><strong>{result.decision === 'ESCALATED' ? 'A support specialist will review this request.' : result.decision === 'APPROVED' ? 'We’ll process the refund to the original payment method.' : 'If you need help, contact support with your order number.'}</strong></article></div><div className="explanation"><p className="eyebrow">Decision details</p>{result.reasons.map((r) => <p key={r}>{r}</p>)}</div><button className="button button--secondary" onClick={onStartOver}>Start another request</button></section> }
function AdminDashboard() { const [refunds, setRefunds] = useState([]), [selected, setSelected] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState('')
  useEffect(() => { api.refunds().then(setRefunds).catch((err) => setError(err.message)).finally(() => setLoading(false)) }, [])
  async function select(id) { try { setSelected(await api.refund(id)) } catch (err) { setError(err.message) } }
  return <section className="admin-shell"><div className="section-heading"><div><p className="eyebrow">Refund operations</p><h1>Refund requests</h1><p>Review customer requests, policy outcomes, and support context.</p></div><div className="queue-count"><strong>{refunds.length}</strong><span>Requests in history</span></div></div>{error && <Notice>{error}</Notice>}<div className="admin-grid"><div className="table-wrap"><div className="table-title"><h2>Recent requests</h2><span>Most recent first</span></div>{loading ? <div className="empty-state">Loading refund requests…</div> : refunds.length === 0 ? <div className="empty-state">No refund requests have been submitted yet.</div> : <table><thead><tr><th>Customer</th><th>Order / product</th><th>Amount</th><th>Decision</th><th>AI classification</th><th>Submitted</th></tr></thead><tbody>{refunds.map((item) => <tr key={item.id} onClick={() => select(item.id)} tabIndex="0" onKeyDown={(e) => e.key === 'Enter' && select(item.id)}><td><strong>{item.customer_name}</strong><small>{item.customer_email}</small></td><td><strong>{item.order_number}</strong><small>{item.product_name}</small></td><td>{money(item.requested_amount)}</td><td><Status value={item.decision} /></td><td><span className="classification">{item.ai_classification.replaceAll('_', ' ')}</span></td><td>{dateTime(item.created_at)}</td></tr>)}</tbody></table>}</div><Detail detail={selected} /></div></section> }
function Detail({ detail }) { if (!detail) return <aside className="detail-panel detail-empty"><span className="detail-icon">↗</span><h2>Request details</h2><p>Select a request to inspect its decision, customer context, and audit trail.</p></aside>
  return <aside className="detail-panel"><div className="detail-top"><div><p className="eyebrow">Request #{detail.id}</p><h2>Request details</h2></div><Status value={detail.decision} /></div><section><h3>Customer request</h3><p>{detail.reason}</p><dl><div><dt>Customer</dt><dd>{detail.customer_name}<small>{detail.customer_email}</small></dd></div><div><dt>Requested</dt><dd>{money(detail.requested_amount)}</dd></div></dl></section><section><h3>Order information</h3><p><strong>{detail.product_name}</strong><br />{detail.order_number} · Ordered {date(detail.order_date)}<br />Order total {money(detail.order_amount)}</p></section><section className="policy-card"><p className="eyebrow">Policy assessment</p>{detail.policy_reasons.map((r) => <p key={r}>{r}</p>)}</section><section className="ai-card"><p className="eyebrow">AI classification</p><strong>{detail.ai_classification.replaceAll('_', ' ')}</strong><p>{detail.ai_response}</p></section><section><h3>Audit trail</h3><ol className="audit">{detail.audit_logs.map((log) => <li key={log.id}><span></span><div><strong>{log.event_type.replaceAll('_', ' ')}</strong><small>{dateTime(log.created_at)}</small></div></li>)}</ol></section></aside> }
function App() { const [view, setView] = useState('customer'); return <><header className="topbar"><a className="brand" href="#customer" onClick={() => setView('customer')}><span>W</span>worknoon</a><nav aria-label="Primary navigation"><button className={view === 'customer' ? 'active' : ''} onClick={() => setView('customer')}>Customer request</button><button className={view === 'admin' ? 'active' : ''} onClick={() => setView('admin')}>Support operations</button></nav><div className="secure"><i />Policy-led decisions</div></header><main>{view === 'customer' ? <CustomerFlow /> : <AdminDashboard />}</main><footer>Worknoon · Refund operations, with decisions grounded in policy.</footer></> }
export default App
